"""Reward functions for GRPO-GR training."""

import re


import numpy as np
import json
import re
from scipy.optimize import linear_sum_assignment
from collections import defaultdict

import nltk
from nltk.translate.bleu_score import sentence_bleu

#from callGPT import call_gpt

def call_gpt(prompt):
    raise NotImplementedError

def gpt_score_reward(prompts, completions, gt_answer, **kwargs):
    """Reward based on gpt-4o evaluation between generated response and correct answer."""
    rewards = []
    # pattern = r'<answer>(.*?)<answer_end>'  # generated by chatGPT
    for i in range(len(gt_answer)):
        if 'dataset' in kwargs and 'ovd' in kwargs['dataset'][i]:
            rewards.append(0.0)
            continue
        response, answer = completions[i], gt_answer[i]
        question = prompts[i][0]['content'][-1]['text'].split('Please answer question: ')[-1]

        reward = 0.0
        # match_pattern = response.split('<answer>', 1)[-1]#re.findall(pattern, response, re.DOTALL) #response.split('<response>')[-1].split('<think_end>')[-1] 
        if '<answer>' in response:
            match_pattern = response.split('<answer>', 1)
            predicted_content = match_pattern[-1].split('</answer>')[0]
            prompt = f"""You are responsible for proofreading the answers, you need to give a score to the model’s answer by referring to the standard answer, based on the given question. The full score is 1 point and the minimum score is 0 points. Please output the score in the json form "{{score: <score>}}". The evaluation criteria require that the closer the model’s answer is to the standard answer, the higher the score.
Question: {question} 
Standard answer: {answer} 
Model’s answer: {predicted_content}"""

            tempt = 0
            while tempt <3:
                tempt+=1
                try:
                    output = re.sub(r'[^\w\s\.]', '', call_gpt(prompt).strip().lower())
                    output_num = output.split("score")[-1][:5]
                    
                    # remove any text that is not a number 
                    output = re.sub(r'[^\d.]', '', output_num)
                    output = float(output)
                    break
                except Exception as e:
                    print("Error in gpt_score_reward: ", e)
                    output =  0
            reward += output
        rewards.append(reward)
    
    return rewards


def gpt_score_reward_1(prompts, completions, gt_answer, **kwargs):
    """Reward based on gpt-4o evaluation between generated response and correct answer."""
    rewards = []
    # pattern = r'<answer>(.*?)<answer_end>'  # generated by chatGPT
    for i in range(len(gt_answer)):
        response, answer = completions[i], gt_answer[i]
        question = prompts[i][0]['content'][-1]['text'].split('Please answer question: ')[-1]

        reward = 0.0
        
        predicted_content = response.strip()
        prompt = f"""You are responsible for proofreading the answers, you need to give a score to the model’s answer by referring to the standard answer, based on the given question. The full score is 1 point and the minimum score is 0 points. Please output the score in the json form "{{score: <score>}}". The evaluation criteria require that the closer the model’s answer is to the standard answer, the higher the score.
Question: {question} 
Standard answer: {answer} 
Model’s answer: {predicted_content}"""
        if response != '':
            tempt = 0
            while tempt <3:
                tempt+=1
                try:
                    output = re.sub(r'[^\w\s\.]', '', call_gpt(prompt).strip().lower())
                    output_num = output.split("score")[-1][:5]
                    
                    # remove any text that is not a number 
                    output = re.sub(r'[^\d.]', '', output_num)
                    output = float(output)
                    break
                except Exception as e:
                    print("Error in gpt_score_reward: ", e)
                    output =  0
            
            reward += output
        rewards.append(reward)
    
    return rewards



def bleu_score_reward(prompts, completions, gt_answer, **kwargs):
    """Reward based on BLEU score between generated response and correct answer."""
    rewards = []
    max_reward = 0.1
    # pattern = r'<answer_start>(.*?)<answer_end>'  # generated by chatGPT
    for i in range(len(gt_answer)):
        response, answer = completions[i], gt_answer[i]
        question = prompts[i][0]['content'][-1]['text'].split('Please answer question: ')[-1]

        reward = 0.0
        # match_pattern = re.findall(pattern, response, re.DOTALL) # re.findall(pattern, response, re.DOTALL)
        
        
        if '<answer>' in response:
            match_pattern = response.split('<answer>', 1)
            predicted_content = match_pattern[-1]
            
            predicted_content = re.sub(r'[^a-zA-Z0-9\s]', ' ', predicted_content)
            answer = re.sub(r'[^a-zA-Z0-9\s]', ' ', answer)
            reward += sentence_bleu([answer.lower().split()], predicted_content.lower().split(), weights=(1, 0, 0, 0))  
        rewards.append(reward * max_reward)
    return rewards

def create_number_mapping():
    """
    Generates a dictionary mapping English number phrases to string digits.
    Covers:
    - 0-19 ("zero"..."nineteen")
    - 20-99 ("twenty"..."ninety nine")
    - Special multipliers ("single", "pair", "dozen")
    """
    mapping = {}
    
    # 1. Basic Units and Teens
    units = [
        "zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine",
        "ten", "eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen", 
        "seventeen", "eighteen", "nineteen"
    ]
    
    for digit, word in enumerate(units):
        mapping[word] = str(digit)
        
    # 2. Tens (20, 30... 90)
    tens = {
        20: "twenty", 30: "thirty", 40: "forty", 50: "fifty", 
        60: "sixty", 70: "seventy", 80: "eighty", 90: "ninety"
    }
    
    # Add exact tens ("twenty" -> "20")
    for val, word in tens.items():
        mapping[word] = str(val)
        
        # Add compounds ("twenty one" -> "21", "twenty-one" -> "21")
        for digit in range(1, 10):
            unit_word = units[digit]
            full_val = str(val + digit)
            
            # "twenty one"
            mapping[f"{word} {unit_word}"] = full_val
            # "twenty-one"
            mapping[f"{word}-{unit_word}"] = full_val

    # 3. Special Quantifiers (Synonyms)
    special_cases = {
        'no': '0', 'none': '0',
        'single': '1', 'a': '1', 'an': '1',
        'couple': '2', 'pair': '2', 'double': '2',
        'triple': '3',
        'dozen': '12'
    }
    mapping.update(special_cases)
    
    return mapping

# Create mapping once globally to save time
NUMBER_MAPPING = create_number_mapping()

def normalize_numbers_in_text(text):
    """
    Replaces English number words in text with digits.
    Example: "There are twenty one cells" -> "There are 21 cells"
    """
    text = text.lower()
    
    # Sort keys by length (descending) so we replace "twenty one" before "one"
    # This prevents "twenty one" becoming "twenty 1"
    sorted_patterns = sorted(NUMBER_MAPPING.keys(), key=len, reverse=True)
    
    # Create a massive regex pattern for all number phrases
    # \b ensures we match "one" but not "bone"
    pattern = r'\b(' + '|'.join(map(re.escape, sorted_patterns)) + r')\b'
    
    def replace_match(match):
        return NUMBER_MAPPING[match.group(0)]
        
    # Execute replacement
    return re.sub(pattern, replace_match, text)

def answer_correctness_reward(prompts, completions, gt_answer, **kwargs):
    rewards = []
    
    for response, answer in zip(completions, gt_answer):
        # 1. Extract content
        if '<answer>' not in response:
            rewards.append(0.0)
            continue
            
        predicted_content = response.split('<answer>', 1)[-1]
        if '</answer>' in predicted_content:
            predicted_content = predicted_content.split('</answer>')[0]
            
        # 2. Normalize (convert "twenty-one" -> "21")
        # Ensure you include the normalize_numbers_in_text function from the previous step
        pred_normalized = normalize_numbers_in_text(predicted_content)
        
        # Clean punctuation
        pred_clean = re.sub(r'[^\w\s]', ' ', pred_normalized).strip()
        gt_clean = str(answer).lower().strip()
        
        reward = 0.0

        if gt_clean.isdigit():
            # --- NEW: Anti-Gaming Filter ---
            # Find all integers in the normalized answer
            # "There are 0 to 1 to 2..." -> ['0', '1', '2'...]
            all_numbers = re.findall(r'\d+', pred_clean)
            unique_numbers = set(all_numbers)
            
            # If the model sprays more than 2 distinct numbers, automatic fail.
            # We allow 2 to handle cases like "It is 4 or 5" (which usually fails the GT check anyway, but isn't spam)
            if len(unique_numbers) > 2:
                reward = 0.0
            elif len(unique_numbers) == 0:
                reward = 0.0
            else:
                # Standard check: Does the exact number exist as a distinct word?
                # if re.search(r'\b' + re.escape(gt_clean) + r'\b', pred_clean):
                #     reward = 1.0
                min_diff = min(abs(int(gt_clean) - int(pred_val)) for pred_val in unique_numbers)
                
                # 4. Apply Inverse Distance Scaling
                # Diff 0 -> 1.0
                # Diff 1 -> 0.5
                # Diff 2 -> 0.33
                reward = 1.0 / (1.0 + min_diff)
                if len(unique_numbers)==2:
                    reward *= 0.5

        elif gt_clean in ['yes', 'no']:
            # (Same existence logic as before)
            has_yes = bool(re.search(r'\byes\b', pred_clean))
            has_no = bool(re.search(r'\bno\b', pred_clean))
            
            if gt_clean == 'yes' and has_yes and not has_no:
                reward = 1.0
            elif gt_clean == 'no' and has_no and not has_yes:
                reward = 1.0
        else:
            if gt_clean in pred_clean:
                reward = 1.0
                
        rewards.append(reward)

    return rewards

def answer_format_reward(prompts, completions, gt_answer, **kwargs):
    """Reward if generated response contains correct answer."""
    rewards = []
    max_reward = 0.5
    keys = ["<answer>"] #  'Result:', '<submit>' '<request><SimpleCalculatorTool>', '<call>', '<response>', 
    for response, answer in zip(completions, gt_answer):
        reward = 0.0
        for key in keys:
            if key in response:
                reward += 1.0
                if len(response.split(key)) == 2:
                    reward += 1.0
        rewards.append(reward/len(keys)/2*max_reward)

    return rewards


def think_and_rethink_format_reward(prompts, completions, gt_answer, **kwargs):
    """Reward if generated response contains correct answer."""
    rewards = []
    max_reward = 0.5
    keys = ["<think>", "</think>", "<rethink>", "</rethink>"] #  'Result:', '<submit>' '<request><SimpleCalculatorTool>', '<call>', '<response>', 
    for response, answer in zip(completions, gt_answer):
        reward = 0.0
        response_original = response
        for key in keys:
            if key in response:
                reward += 1.0
                # if len(response.split(key)) == 2:
                #     reward += 1.0
                response = response.split(key)[-1]
        if reward == len(keys):
            #check if thinking content is repeating
            try:
                response_list = response_original.split("<think>")[-1].split("</think>")[0].strip()
                assert isinstance(response_list, str) and len(response_list)>1 # at least 2 letters
                response_list = re.sub(r'[^a-zA-Z0-9\s]', ' ', response_list)
                response_list = response_list.split(' ')
                assert len(response_list)>1 # at least 2 words
                reward += 1.0
            except Exception as e:
                print("Error in think_format_reward: ", e)
        rewards.append(reward/(len(keys)+1)*max_reward) 

    return rewards



def grounded_region_specific_thinking_format_reward_think_rethink(prompts, completions, gt_answer, **kwargs):
    rewards = []
    ind = -1
    for response, answer in zip(completions, gt_answer):
        ind += 1
        if not '<rethink>' in response:
            reward = 0.0
            rewards.append(reward)
            continue
            
        response = response.split("<rethink>")[0]
        reward = 0.0
        pattern = r'\b\d+,\s*\d+,\s*\d+,\s*\d+\b'
        matches = re.findall(pattern, response)
                
        # if len(matches) > 0 and not (answer.lower() == 'no' or int(answer) == 0):
        #     reward += 0.5
        #     if answer.lower() == 'yes':
        #         reward += 0.5
        # elif len(matches) == 0 and answer.lower() == 'no':
        #     reward += 1

        if (kwargs['dataset'][0] == 'tallyqa' or 'txl_count' in kwargs['dataset'][ind]):
            try:
                # if len(matches) == int(answer):
                #     reward += 1
                n_bbox = len(matches)
                target = int(answer)
                reward += 1.5/(1+abs(target-n_bbox))
            except ValueError:
                pass
        else:
            if len(matches) > 0 and answer.lower() != 'no':
                reward += 0.5
                if answer.lower() == 'yes':
                    reward += 0.5
            elif len(matches) == 0 and answer.lower() == 'no':
                reward += 1

                
        rewards.append(reward) 

    return rewards

def zipngram(text: str, ngram_size: int):
    words = text.lower().split()
    return zip(*[words[i:] for i in range(ngram_size)])

def repetitive_reward(prompts, completions, completion_ids, gt_answer, **kwargs):
    """Reward function that checks if the completion has repeting workds."""
    ngram_size = 8
    max_reward = 0.5
    rewards = []
    pad_token_id = 151643
    # iterate over each generated sequence in the batch
    for ids, completion in zip(completion_ids, completions):
        
        # for words repeating
        
        if completion == "":
            rewards.append(max_reward)
            continue
        if len(completion.split()) < ngram_size:
            rewards.append(max_reward)
            continue
        repeat_count = 0
        total = 0
        tokens = completion.split()


        for i in range(len(tokens) - ngram_size):
            ng1 = tuple(tokens[i:i+ngram_size])
            ng2 = tuple(tokens[i+ngram_size:i+ngram_size+ngram_size])
            total += 1
            if ng1 == ng2:
                repeat_count += 1

        if total == 0:
            reward = 1.0
        else:
            reward = 1.0 - (repeat_count / total)
        
        
        
        
        # convert to Python list
        ids_list = ids.tolist()
        # drop everything from the first pad_token_id onward
        if pad_token_id is not None:
            if pad_token_id in ids_list:
                ids_list = ids_list[: ids_list.index(pad_token_id)]
        # if too short to form two full n‑grams, give full reward
        if len(ids_list) < 2 * ngram_size:
            rewards.append(max_reward)
            continue

        repeat_count = 0
        total_pairs = 0
        # compare each n‑gram with the immediately following one
        for i in range(len(ids_list) - 2*ngram_size + 1):
            ng1 = tuple(ids_list[i : i + ngram_size])
            ng2 = tuple(ids_list[i + ngram_size : i + 2*ngram_size])
            total_pairs += 1
            if ng1 == ng2:
                repeat_count += 1

        # if there were no valid comparisons, treat as non‑repetitive
        if total_pairs == 0:
            score = 1.0
        else:
            score = 1.0 - (repeat_count / total_pairs)

        # scale into [0, max_reward]
        rewards.append((score - (1-reward)) * max_reward)
    return rewards


def _extract_bboxes_from_text(text):
    segments = []
    if "<box>" in text and "</box>" in text:
        segments.append(text.split("<box>", 1)[1].split("</box>", 1)[0])
    if "bbox_2d" in text:
        segments.append(text)
    if not segments:
        segments = [text]

    pattern = re.compile(r"\b\d+,\s*\d+,\s*\d+,\s*\d+\b")
    bboxes = []
    for segment in segments:
        for match in pattern.findall(segment):
            bbox = [float(value.strip()) for value in match.split(",")]
            if len(bbox) == 4:
                bboxes.append(bbox)
    return bboxes


def _sanitize_bbox(bbox):
    x1, y1, x2, y2 = bbox
    x_min, x_max = sorted([x1, x2])
    y_min, y_max = sorted([y1, y2])
    if x_max <= x_min or y_max <= y_min:
        return None
    return (x_min, y_min, x_max, y_max)


def _union_area(rects):
    if not rects:
        return 0.0
    xs = sorted({rect[0] for rect in rects}.union({rect[2] for rect in rects}))
    area = 0.0
    for i in range(len(xs) - 1):
        x_left = xs[i]
        x_right = xs[i + 1]
        if x_right <= x_left:
            continue
        intervals = []
        for x1, y1, x2, y2 in rects:
            if x1 < x_right and x2 > x_left:
                intervals.append((y1, y2))
        if not intervals:
            continue
        intervals.sort()
        merged = []
        cur_start, cur_end = intervals[0]
        for start, end in intervals[1:]:
            if start <= cur_end:
                cur_end = max(cur_end, end)
            else:
                merged.append((cur_start, cur_end))
                cur_start, cur_end = start, end
        merged.append((cur_start, cur_end))
        y_total = sum(end - start for start, end in merged)
        area += (x_right - x_left) * y_total
    return area


def _intersection_union_areas(pred_rects, gt_rects):
    pred_area = _union_area(pred_rects)
    gt_area = _union_area(gt_rects)
    intersections = []
    for px1, py1, px2, py2 in pred_rects:
        for gx1, gy1, gx2, gy2 in gt_rects:
            ix1 = max(px1, gx1)
            iy1 = max(py1, gy1)
            ix2 = min(px2, gx2)
            iy2 = min(py2, gy2)
            if ix2 > ix1 and iy2 > iy1:
                intersections.append((ix1, iy1, ix2, iy2))
    intersection_area = _union_area(intersections)
    union_area = pred_area + gt_area - intersection_area
    return intersection_area, union_area


def grounded_region_bbox_giou_reward(prompts, completions, bboxs=None, width=None, height=None, normalized_bboxs=False, use_giou=False, **kwargs):
    """Reward based on generalized IoU (GIoU) between predicted and ground-truth bbox unions."""
    rewards = []
    width_list = width or [None] * len(completions)
    height_list = height or [None] * len(completions)
    for response, gt_boxes, img_w, img_h in zip(completions, bboxs, width_list, height_list):
        if not gt_boxes:
            rewards.append(0.0)
            continue

        pred_boxes = _extract_bboxes_from_text(response)
        if normalized_bboxs and img_w and img_h:
            pred_boxes = [
                [box[0] * img_w, box[1] * img_h, box[2] * img_w, box[3] * img_h]
                for box in pred_boxes
            ]

        pred_rects = []
        for box in pred_boxes:
            rect = _sanitize_bbox(box)
            if rect:
                pred_rects.append(rect)

        gt_rects = []
        for box in gt_boxes:
            rect = _sanitize_bbox(box)
            if rect:
                gt_rects.append(rect)

        if not pred_rects or not gt_rects:
            rewards.append(0.0)
            continue

        intersection_area, union_area = _intersection_union_areas(pred_rects, gt_rects)
        if union_area <= 0:
            rewards.append(0.0)
            continue

        iou = intersection_area / union_area
        # all_rects = pred_rects + gt_rects
        # x_min = min(rect[0] for rect in all_rects)
        # y_min = min(rect[1] for rect in all_rects)
        # x_max = max(rect[2] for rect in all_rects)
        # y_max = max(rect[3] for rect in all_rects)
        # c_area = max(0.0, (x_max - x_min) * (y_max - y_min))
        # if c_area <= 0:
        #     rewards.append(0.0)
        #     continue

        if use_giou:
            all_rects = pred_rects + gt_rects
            x_min = min(rect[0] for rect in all_rects)
            y_min = min(rect[1] for rect in all_rects)
            x_max = max(rect[2] for rect in all_rects)
            y_max = max(rect[3] for rect in all_rects)
            c_area = max(0.0, (x_max - x_min) * (y_max - y_min))
            if c_area <= 0:
                rewards.append(0.0)
                continue
            giou = iou - (c_area - union_area) / c_area
            rewards.append(giou)
        else:
            rewards.append(iou)

    return rewards


def grounded_region_bbox_repetitive_loss(prompts, completions, width=None, height=None, normalized_bboxs=False, **kwargs):
    """Penalty for repeating identical bounding boxes in the completion."""
    rewards = []
    width_list = width or [None] * len(completions)
    height_list = height or [None] * len(completions)
    for response, img_w, img_h in zip(completions, width_list, height_list):
        pred_boxes = _extract_bboxes_from_text(response)
        if normalized_bboxs and img_w and img_h:
            pred_boxes = [
                [box[0] * img_w, box[1] * img_h, box[2] * img_w, box[3] * img_h]
                for box in pred_boxes
            ]

        pred_rects = []
        for box in pred_boxes:
            rect = _sanitize_bbox(box)
            if rect:
                pred_rects.append(rect)

        if len(pred_rects) < 2:
            rewards.append(0.0)
            continue

        rounded = [tuple(int(round(value)) for value in rect) for rect in pred_rects]
        total = len(rounded)
        unique = len(set(rounded))
        repeat_ratio = 1.0 - (unique / total)
        rewards.append(-repeat_ratio)

    return rewards


def _giou(rect_a, rect_b, use_giou=True):
    ax1, ay1, ax2, ay2 = rect_a
    bx1, by1, bx2, by2 = rect_b
    ix1 = max(ax1, bx1)
    iy1 = max(ay1, by1)
    ix2 = min(ax2, bx2)
    iy2 = min(ay2, by2)
    intersection = max(0.0, ix2 - ix1) * max(0.0, iy2 - iy1)
    area_a = max(0.0, ax2 - ax1) * max(0.0, ay2 - ay1)
    area_b = max(0.0, bx2 - bx1) * max(0.0, by2 - by1)
    union = area_a + area_b - intersection
    if union <= 0:
        return 0.0
    iou = intersection / union
    if not use_giou:
        return iou
    cx1 = min(ax1, bx1)
    cy1 = min(ay1, by1)
    cx2 = max(ax2, bx2)
    cy2 = max(ay2, by2)
    c_area = max(0.0, cx2 - cx1) * max(0.0, cy2 - cy1)
    if c_area <= 0:
        return iou
    return iou - (c_area - union) / c_area


def _pairwise_giou(pred_rects, gt_rects, use_giou=True):
    if not pred_rects or not gt_rects:
        return np.zeros((len(pred_rects), len(gt_rects)), dtype=np.float32)
    giou_matrix = np.zeros((len(pred_rects), len(gt_rects)), dtype=np.float32)
    for i, pred in enumerate(pred_rects):
        for j, gt in enumerate(gt_rects):
            giou_matrix[i, j] = _giou(pred, gt, use_giou=True)
    return giou_matrix


def grounded_region_bbox_hungarian_giou_reward(
    prompts,
    completions,
    bboxs=None,
    width=None,
    height=None,
    normalized_bboxs=False,
    redundant_penalty=0.05,
    use_giou=True,
    **kwargs,
):
    """Reward using Hungarian matching and per-target GIoU with redundant prediction penalty."""
    rewards = []
    width_list = width or [None] * len(completions)
    height_list = height or [None] * len(completions)
    for response, gt_boxes, img_w, img_h in zip(completions, bboxs, width_list, height_list):
        if not gt_boxes:
            rewards.append(0.0)
            continue

        pred_boxes = _extract_bboxes_from_text(response)
        if normalized_bboxs and img_w and img_h:
            pred_boxes = [
                [box[0] * img_w, box[1] * img_h, box[2] * img_w, box[3] * img_h]
                for box in pred_boxes
            ]

        pred_rects = []
        for box in pred_boxes:
            rect = _sanitize_bbox(box)
            if rect:
                pred_rects.append(rect)

        gt_rects = []
        for box in gt_boxes:
            rect = _sanitize_bbox(box)
            if rect:
                gt_rects.append(rect)

        if not gt_rects:
            rewards.append(0.0)
            continue

        if not pred_rects:
            rewards.append(0.0)
            continue

        giou_matrix = _pairwise_giou(pred_rects, gt_rects, use_giou=use_giou)
        cost_matrix = 1.0 - giou_matrix
        if hasattr(cost_matrix,"detach"):
            cost_matrix = cost_matrix.detach().cpu().numpy()
        else:
            cost_matrix = np.asarray(cost_matrix)
        row_ind, col_ind = linear_sum_assignment(cost_matrix)

        matched_giou = {gt_idx: giou_matrix[pred_idx, gt_idx] for pred_idx, gt_idx in zip(row_ind, col_ind)}

        per_target_scores = [matched_giou.get(gt_idx, 0.0) for gt_idx in range(len(gt_rects))]
        avg_giou = float(np.mean(per_target_scores)) if per_target_scores else 0.0
        if redundant_penalty != 0:
            redundant_count = max(0, len(pred_rects) - len(row_ind))
            avg_giou -= redundant_penalty * redundant_count
        rewards.append(avg_giou)

    return rewards
